version: '3.9'

services:
  java-app:
    container_name: java-app
    image: blazo-bootcamp-docker-jwt:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java-bootcamp-db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java-bootcamp-db
  java-bootcamp-db:
    container_name: java-bootcamp-db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
