version: '3.9'

services:
  java-app:
    container_name: java-app
    image: blazo-bootcamp-docker-jwt:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java-bootcamp-db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      # The secret key must be an HMAC hash string of 256 bits; otherwise, the token generation will throw an error.
      - JWT_SECRET_KEY=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      - JWT_EXPIRATION=43200000
      # Bootstrap admin information
      - ADMIN_EMAIL=admin@gmail.com
      - ADMIN_PASSWORD=admin
      - ADMIN_NAME=Super
      - ADMIN_LASTNAME=Admin
    depends_on:
      - java-bootcamp-db
  java-bootcamp-db:
    container_name: java-bootcamp-db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
